# Generated by Django 5.2.17 on 2026-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaildelivery',
            options={'verbose_name': 'envoi email', 'verbose_name_plural': 'envois email'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='dedupe_key',
            field=models.CharField(max_length=120, verbose_name='clé de déduplication'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='dernière erreur'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='destinataire'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='envoyé le'),
        ),
        migrations.AlterField(
            model_name='emaildelivery',
            name='subject',
            field=models.CharField(max_length=180, verbose_name='objet'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(max_length=120, verbose_name='clé de déduplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reminder', 'Rappel'), ('system', 'Système'), ('invitation', 'Invitation')], default='system', max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lue le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=180, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='lien'),
        ),
    ]
