# Generated by Django 5.2.17 on 2026-08-17 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_emaildelivery_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family", models.CharField(max_length=32, verbose_name="famille")),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, verbose_name="dans l'application"
                    ),
                ),
                (
                    "email",
                    models.BooleanField(default=True, verbose_name="aussi par email"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "préférence de notification",
                "verbose_name_plural": "préférences de notification",
                "ordering": ["family"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "family"), name="unique_preference_per_family"
                    )
                ],
            },
        ),
    ]
