# Generated by Django 5.2.17 on 2026-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['starts_at'], 'verbose_name': 'événement', 'verbose_name_plural': 'événements'},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['scheduled_for'], 'verbose_name': 'rappel', 'verbose_name_plural': 'rappels'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'priority', 'due_at', 'title'], 'verbose_name': 'tâche', 'verbose_name_plural': 'tâches'},
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='journée entière'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='email_reminder',
            field=models.BooleanField(default=True, verbose_name='rappel par email'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='ends_at',
            field=models.DateTimeField(verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=180, verbose_name='lieu'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rappel le'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='starts_at',
            field=models.DateTimeField(verbose_name='début'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=180, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tentatives'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='email',
            field=models.BooleanField(default=True, verbose_name='envoi par email'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='internal',
            field=models.BooleanField(default=True, verbose_name='notification interne'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='dernière erreur'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_for',
            field=models.DateTimeField(db_index=True, verbose_name='prévu pour'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='envoyé le'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=12, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='échéance'),
        ),
        migrations.AlterField(
            model_name='task',
            name='email_reminder',
            field=models.BooleanField(default=True, verbose_name='rappel par email'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Basse'), (2, 'Normale'), (1, 'Haute')], default=2, verbose_name='priorité'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='rappel le'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminée')], default='todo', max_length=16, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=180, verbose_name='intitulé'),
        ),
    ]
