# Generated by Django 5.2.17 on 2026-08-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_calendarevent_options_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='planner.calendarevent', verbose_name='série'),
        ),
    ]
