# Generated by Django 5.2.17 on 2026-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_libraryitem_purpose'),
        ('planner', '0005_taskfocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='library.libraryitem', verbose_name='ressources'),
        ),
    ]
