# Generated by Django 5.2.17 on 2026-09-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_task_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='planner.task', verbose_name='tâche'),
        ),
    ]
