# Generated by Django 5.2.17 on 2026-08-10 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('today', 'Aujourd’hui'), ('tasks', 'Tâches prioritaires'), ('reminders', 'Rappels'), ('recent', 'Contenus récents'), ('formations', 'Formations'), ('quick_note', 'Note rapide'), ('sablier', 'Sablier')], max_length=24)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'kind'), name='unique_widget_per_user')],
            },
        ),
    ]
