# Generated by Django 5.2.17 on 2026-08-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardwidget',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'bloc du tableau de bord', 'verbose_name_plural': 'blocs du tableau de bord'},
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='kind',
            field=models.CharField(choices=[('today', 'Aujourd’hui'), ('tasks', 'Tâches prioritaires'), ('reminders', 'Rappels'), ('recent', 'Contenus récents'), ('formations', 'Formations'), ('quick_note', 'Note rapide'), ('sablier', 'Sablier')], max_length=24, verbose_name='bloc'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
