# Generated by Django 5.2.17 on 2026-08-11 05:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'invitation', 'verbose_name_plural': 'invitations'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profils'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='acceptée le'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='expire le'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invité par'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#7C6CFF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Utilisez une couleur hexadécimale, par ex. #7C6CFF.')], verbose_name='couleur d’accent'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='audio_quota_mb',
            field=models.PositiveIntegerField(default=1024, verbose_name='quota audio (Mo)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nom affiché'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='email vérifié le'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('system', 'Système'), ('light', 'Clair'), ('dark', 'Sombre')], default='system', max_length=10, verbose_name='thème'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/Cayenne', max_length=64, verbose_name='fuseau horaire'),
        ),
    ]
