# Generated by Django 5.2.17 on 2026-08-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_audio_quota_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='audio_quota_mb',
            field=models.PositiveIntegerField(default=10240, help_text='Un compte administrateur bénéficie au minimum de AUDIO_ADMIN_QUOTA_MB, quelle que soit la valeur inscrite ici.', verbose_name='quota audio (Mo)'),
        ),
    ]
