# Generated by Django 5.2.17 on 2026-09-15 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_audio_quota_help'),
        ('formations', '0013_progressevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_path',
            field=models.ForeignKey(blank=True, help_text='Celle que l’accueil suit. Sans choix, il suit la première formation active qui a une période en cours.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='formations.learningpath', verbose_name='formation principale'),
        ),
    ]
