# Generated by Django 5.2.17 on 2026-08-10 04:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('training_type', models.CharField(blank=True, max_length=120)),
                ('level_label', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée')], default='active', max_length=12)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('resources', models.ManyToManyField(blank=True, related_name='learning_units', to='library.libraryitem')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('resources', models.ManyToManyField(blank=True, related_name='competencies', to='library.libraryitem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='formations.learningunit')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('unit_label', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_definitions', to='formations.learningpath')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formations.metricdefinition')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='formations.learningunit')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='formations.learningpath')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='learningunit',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='formations.period'),
        ),
        migrations.CreateModel(
            name='ProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('notes', models.TextField(blank=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='formations.competency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('unit', 'title'), name='unique_competency_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.UniqueConstraint(fields=('path', 'key'), name='unique_metric_key_per_path'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.UniqueConstraint(fields=('definition', 'unit'), name='unique_metric_value_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('path', 'title'), name='unique_period_per_path'),
        ),
        migrations.AddConstraint(
            model_name='learningunit',
            constraint=models.UniqueConstraint(fields=('period', 'title'), name='unique_unit_per_period'),
        ),
        migrations.AddConstraint(
            model_name='progressrecord',
            constraint=models.UniqueConstraint(fields=('owner', 'competency'), name='unique_progress_per_competency'),
        ),
    ]
