# Generated by Django 5.2.17 on 2026-08-10 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressrecord',
            name='mastery_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non abordé'), (1, 'Découvert'), (2, 'En cours'), (3, 'Acquis'), (4, 'Maîtrisé')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
