# Generated by Django 5.2.17 on 2026-08-11 05:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_alter_progressrecord_mastery_level'),
        ('library', '0003_alter_folder_options_alter_libraryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competency',
            options={'ordering': ['order', 'title'], 'verbose_name': 'compétence', 'verbose_name_plural': 'compétences'},
        ),
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['title'], 'verbose_name': 'formation', 'verbose_name_plural': 'formations'},
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'ordering': ['order', 'title'], 'verbose_name': 'module', 'verbose_name_plural': 'modules'},
        ),
        migrations.AlterModelOptions(
            name='metricdefinition',
            options={'ordering': ['order', 'label'], 'verbose_name': 'colonne de suivi', 'verbose_name_plural': 'colonnes de suivi'},
        ),
        migrations.AlterModelOptions(
            name='metricvalue',
            options={'verbose_name': 'valeur de suivi', 'verbose_name_plural': 'valeurs de suivi'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['order', 'title'], 'verbose_name': 'période', 'verbose_name_plural': 'périodes'},
        ),
        migrations.AlterModelOptions(
            name='progressrecord',
            options={'verbose_name': 'progression', 'verbose_name_plural': 'progressions'},
        ),
        migrations.AlterField(
            model_name='competency',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='competencies', to='library.libraryitem', verbose_name='ressources'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='title',
            field=models.CharField(max_length=220, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='formations.learningunit', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='level_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée')], default='active', max_length=12, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='title',
            field=models.CharField(max_length=180, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='training_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='type de formation'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='formations.period', verbose_name='période'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='learning_units', to='library.libraryitem', verbose_name='ressources'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='title',
            field=models.CharField(max_length=180, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='key',
            field=models.SlugField(max_length=40, verbose_name='clé'),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='label',
            field=models.CharField(max_length=80, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_definitions', to='formations.learningpath', verbose_name='formation'),
        ),
        migrations.AlterField(
            model_name='metricdefinition',
            name='unit_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='unité'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formations.metricdefinition', verbose_name='colonne'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='formations.learningunit', verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='metricvalue',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur'),
        ),
        migrations.AlterField(
            model_name='period',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='period',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='formations.learningpath', verbose_name='formation'),
        ),
        migrations.AlterField(
            model_name='period',
            name='title',
            field=models.CharField(max_length=140, verbose_name='intitulé'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='temps réel (h)'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='formations.competency', verbose_name='compétence'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='mastery_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non abordé'), (1, 'Découvert'), (2, 'En cours'), (3, 'Acquis'), (4, 'Maîtrisé')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='niveau de maîtrise'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='commentaires'),
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='travail personnel estimé (h)'),
        ),
    ]
