# Generated by Django 5.2.17 on 2026-08-12 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_competency_path_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressrecord',
            name='assessed_at',
            field=models.DateTimeField(blank=True, help_text='Renseignée automatiquement quand le niveau change.', null=True, verbose_name='dernière autoévaluation'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='level_origin',
            field=models.CharField(choices=[('manual', 'Déclaré par moi'), ('suggested', 'Suggéré, à confirmer')], default='manual', help_text="Un niveau suggéré reste une proposition tant qu'il n'est pas confirmé.", max_length=10, verbose_name='origine du niveau'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='target_date',
            field=models.DateField(blank=True, help_text="Une date d'examen, par exemple.", null=True, verbose_name='à atteindre le'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='target_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Non abordé'), (1, 'Découvert'), (2, 'En cours'), (3, 'Acquis'), (4, 'Maîtrisé')], help_text="Le niveau que vous visez, s'il diffère de la maîtrise complète.", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='objectif de maîtrise'),
        ),
    ]
