# Generated by Django 5.2.17 on 2026-08-12 03:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_progress_self_assessment'),
        ('library', '0004_libraryitem_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='intitulé')),
                ('kind', models.CharField(choices=[('homework', 'Devoir maison'), ('test', 'Contrôle'), ('midterm', 'Partiel'), ('oral', 'Oral'), ('project', 'Projet'), ('exam', 'Examen'), ('other', 'Autre')], default='test', max_length=10, verbose_name='type')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='date et heure')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, help_text="Poids de l'évaluation dans la moyenne de la matière.", max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='coefficient')),
                ('scale', models.DecimalField(decimal_places=2, default=20, help_text='La note maximale possible : 20, 100, 5…', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='barème')),
                ('status', models.CharField(choices=[('planned', 'Prévue'), ('taken', 'Passée'), ('marked', 'Corrigée'), ('cancelled', 'Annulée')], default='planned', max_length=10, verbose_name='état')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('competencies', models.ManyToManyField(blank=True, related_name='assessments', to='formations.competency', verbose_name='compétences évaluées')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='formations.period', verbose_name='période')),
                ('resources', models.ManyToManyField(blank=True, related_name='assessments', to='library.libraryitem', verbose_name='ressources de préparation')),
                ('unit', models.ForeignKey(blank=True, help_text="Facultatif : un examen transversal n'en concerne aucune en particulier.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='formations.learningunit', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-scheduled_for', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text="Laissez vide en cas d'absence.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='note obtenue')),
                ('scale', models.DecimalField(decimal_places=2, help_text="Repris de l'évaluation ; modifiable si le barème réel a différé.", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='barème appliqué')),
                ('absent', models.BooleanField(default=False, verbose_name='absence')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire du correcteur')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='publiée le')),
                ('self_review', models.TextField(blank=True, help_text='Ce que vous en retenez : ce qui a manqué, ce qui a bien marché.', verbose_name='mon appréciation')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='formations.assessment', verbose_name='évaluation')),
            ],
            options={
                'verbose_name': 'résultat',
                'verbose_name_plural': 'résultats',
            },
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('coefficient__gte', 0)), name='assessment_coefficient_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('scale__gt', 0)), name='assessment_scale_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__gte', 0), _connector='OR'), name='result_score_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.CheckConstraint(condition=models.Q(('scale__gt', 0)), name='result_scale_positive'),
        ),
    ]
