# Generated by Django 5.2.17 on 2026-08-12 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='weight_metric',
            field=models.ForeignKey(blank=True, help_text="La colonne qui porte le poids des matières — ECTS, coefficient. Nécessaire pour calculer une moyenne de période ; laissez vide si cela n'a pas de sens.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighting_for', to='formations.metricdefinition', verbose_name='colonne de pondération'),
        ),
    ]
