# Generated by Django 5.2.17 on 2026-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0011_split_progress_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='time_suggests_level',
            field=models.BooleanField(default=True, help_text='Quand le temps travaillé atteint un quart du travail estimé, proposer « découvert », puis « en cours », « acquis » et « maîtrisé » aux quarts suivants. Une proposition ne remplace jamais un niveau que vous avez déclaré.', verbose_name='paliers de temps'),
        ),
    ]
