# Generated by Django 5.2.17 on 2026-08-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0012_time_suggests_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_level', models.PositiveSmallIntegerField(choices=[(0, 'Non abordé'), (1, 'Découvert'), (2, 'En cours'), (3, 'Acquis'), (4, 'Maîtrisé')], verbose_name='niveau précédent')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Non abordé'), (1, 'Découvert'), (2, 'En cours'), (3, 'Acquis'), (4, 'Maîtrisé')], verbose_name='niveau atteint')),
                ('origin', models.CharField(choices=[('manual', 'Déclaré par moi'), ('suggested', 'Suggéré, à confirmer')], max_length=10, verbose_name='origine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='formations.progressrecord', verbose_name='progression')),
            ],
            options={
                'verbose_name': 'changement de niveau',
                'verbose_name_plural': 'changements de niveau',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['record', 'created_at'], name='progress_event_record_idx')],
            },
        ),
    ]
