# Generated by Django 5.2.17 on 2026-08-10 04:09

import django.core.validators
import django.db.models.deletion
import sablier.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('artist', models.CharField(blank=True, max_length=180)),
                ('file', models.FileField(upload_to=sablier.models.audio_upload_path)),
                ('mime_type', models.CharField(max_length=80)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploading', 'Téléversement'), ('validating', 'Validation'), ('ready', 'Prête'), ('rejected', 'Refusée')], default='validating', max_length=12)),
                ('rejection_reason', models.CharField(blank=True, max_length=240)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FocusPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_duration_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)])),
                ('session_intention', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(choices=[('ring', 'Anneau'), ('hourglass', 'Sablier'), ('digital', 'Digital'), ('zen', 'Zen')], default='hourglass', max_length=16)),
                ('ambience', models.CharField(choices=[('concentration', 'Concentration'), ('calm', 'Calme'), ('energy', 'Énergie'), ('night', 'Nocturne')], default='concentration', max_length=16)),
                ('focus_level', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('warning_seconds', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)])),
                ('soundscape_enabled', models.BooleanField(default=False)),
                ('end_sound_enabled', models.BooleanField(default=True)),
                ('accent_color', models.CharField(default='#8878FF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Couleur hexadécimale invalide.')])),
                ('background_image', models.ImageField(blank=True, upload_to=sablier.models.focus_background_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='focus_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='sablier.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='sablier.audiotrack')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='sablier.PlaylistTrack', to='sablier.audiotrack'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='unique_track_per_playlist'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('owner', 'title'), name='unique_playlist_title_per_user'),
        ),
    ]
