# Generated by Django 5.2.17 on 2026-08-11 05:00

import django.core.validators
import django.db.models.deletion
import sablier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sablier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiotrack',
            options={'ordering': ['title', 'pk'], 'verbose_name': 'piste audio', 'verbose_name_plural': 'pistes audio'},
        ),
        migrations.AlterModelOptions(
            name='focuspreference',
            options={'verbose_name': 'préférence Sablier', 'verbose_name_plural': 'préférences Sablier'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['title'], 'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'piste de playlist', 'verbose_name_plural': 'pistes de playlist'},
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='artist',
            field=models.CharField(blank=True, max_length=180, verbose_name='artiste'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='durée (s)'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='file',
            field=models.FileField(upload_to=sablier.models.audio_upload_path, verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='taille'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='mime_type',
            field=models.CharField(max_length=80, verbose_name='type MIME'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=240, verbose_name='motif du refus'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='status',
            field=models.CharField(choices=[('uploading', 'Téléversement'), ('validating', 'Validation'), ('ready', 'Prête'), ('rejected', 'Refusée')], default='validating', max_length=12, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='audiotrack',
            name='title',
            field=models.CharField(max_length=180, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='accent_color',
            field=models.CharField(default='#8878FF', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Couleur hexadécimale invalide.')], verbose_name='couleur d’accent'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='ambience',
            field=models.CharField(choices=[('concentration', 'Concentration'), ('calm', 'Calme'), ('energy', 'Énergie'), ('night', 'Nocturne')], default='concentration', max_length=16, verbose_name='ambiance'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='background_image',
            field=models.ImageField(blank=True, upload_to=sablier.models.focus_background_path, verbose_name='image de fond'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='default_duration_seconds',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)], verbose_name='durée par défaut (s)'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='end_sound_enabled',
            field=models.BooleanField(default=True, verbose_name='son de fin'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='focus_level',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='niveau de concentration'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='mode',
            field=models.CharField(choices=[('ring', 'Anneau'), ('hourglass', 'Sablier'), ('digital', 'Digital'), ('zen', 'Zen')], default='hourglass', max_length=16, verbose_name='visualisation'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='session_intention',
            field=models.CharField(blank=True, max_length=80, verbose_name='intention'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='soundscape_enabled',
            field=models.BooleanField(default=False, verbose_name='son ambiant'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='warning_seconds',
            field=models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)], verbose_name='alerte finale (s)'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=160, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='sablier.PlaylistTrack', to='sablier.audiotrack', verbose_name='pistes'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='sablier.playlist', verbose_name='playlist'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='sablier.audiotrack', verbose_name='piste'),
        ),
    ]
