# Generated by Django 5.2.17 on 2026-08-11 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_alter_competency_options_alter_learningpath_options_and_more'),
        ('sablier', '0002_alter_audiotrack_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intention', models.CharField(blank=True, max_length=80, verbose_name='intention')),
                ('started_at', models.DateTimeField(verbose_name='début')),
                ('seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)], verbose_name='durée (s)')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='reportée le')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='formations.competency', verbose_name='compétence')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'session de concentration',
                'verbose_name_plural': 'sessions de concentration',
                'ordering': ['-started_at'],
            },
        ),
    ]
