# Generated by Django 5.2.17 on 2026-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sablier', '0003_focussession'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuspreference',
            name='custom_accent',
            field=models.BooleanField(default=False, verbose_name='utiliser ma couleur plutôt que celle de l’ambiance'),
        ),
    ]
