# Generated by Django 5.2.17 on 2026-08-11 21:36

from django.db import migrations, models

# Valeurs figées volontairement plutôt qu'importées de scenes.py : une migration doit
# décrire l'état du monde au moment où elle a été écrite, et ne pas changer de sens
# quand la liste des ambiances évoluera.
REPLACEMENTS = {"calm": "ocean", "energy": "ete", "night": "nuit"}
KNOWN = (
    "concentration",
    "printemps",
    "ete",
    "automne",
    "hiver",
    "pluie",
    "ocean",
    "sahara",
    "nuit",
)


def move_to_the_new_scenes(apps, schema_editor):
    """Les ambiances abstraites deviennent les décors qui leur ressemblent le plus.

    Sans cela, une préférence enregistrée sur « calme » resterait sur une valeur que le
    modèle ne connaît plus : le sélecteur s'afficherait vide et aucun décor ne
    correspondrait.
    """
    preferences = apps.get_model("sablier", "FocusPreference")
    for previous, replacement in REPLACEMENTS.items():
        preferences.objects.filter(ambience=previous).update(ambience=replacement)
    preferences.objects.exclude(ambience__in=KNOWN).update(ambience="concentration")


class Migration(migrations.Migration):
    dependencies = [
        ("sablier", "0004_focuspreference_custom_accent"),
    ]

    operations = [
        migrations.RunPython(move_to_the_new_scenes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='focuspreference',
            name='soundscape_enabled',
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='ambience',
            field=models.CharField(choices=[('concentration', 'Concentration'), ('printemps', 'Printemps'), ('ete', 'Été'), ('automne', 'Automne'), ('hiver', 'Hiver'), ('pluie', 'Pluie'), ('ocean', 'Océan'), ('sahara', 'Sahara'), ('nuit', 'Nuit')], default='concentration', max_length=16, verbose_name='ambiance'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='mode',
            field=models.CharField(choices=[('ring', 'Anneau'), ('hourglass', 'Sablier'), ('wave', 'Marée'), ('candle', 'Bougie'), ('beads', 'Perles'), ('moon', 'Lune'), ('digital', 'Digital'), ('zen', 'Zen')], default='hourglass', max_length=16, verbose_name='visualisation'),
        ),
    ]
