# Generated by Django 5.2.17 on 2026-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sablier', '0005_remove_focuspreference_soundscape_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuspreference',
            name='decor_density',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Aucun décor'), (1, 'Léger'), (2, 'Normal'), (3, 'Dense')], default=2, verbose_name='densité du décor'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='ambience',
            field=models.CharField(choices=[('concentration', 'Concentration'), ('printemps', 'Printemps'), ('ete', 'Été'), ('automne', 'Automne'), ('hiver', 'Hiver'), ('pluie', 'Pluie'), ('ocean', 'Océan'), ('sahara', 'Sahara'), ('foret', 'Forêt'), ('orage', 'Orage'), ('braises', 'Braises'), ('aurore', 'Aurore'), ('nuit', 'Nuit')], default='concentration', max_length=16, verbose_name='ambiance'),
        ),
        migrations.AlterField(
            model_name='focuspreference',
            name='mode',
            field=models.CharField(choices=[('ring', 'Anneau'), ('hourglass', 'Sablier'), ('wave', 'Marée'), ('candle', 'Bougie'), ('beads', 'Perles'), ('moon', 'Lune'), ('bars', 'Colonnes'), ('spiral', 'Spirale'), ('sun', 'Soleil'), ('digital', 'Digital'), ('zen', 'Zen')], default='hourglass', max_length=16, verbose_name='visualisation'),
        ),
    ]
