# Generated by Django 5.2.17 on 2026-08-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sablier', '0006_focuspreference_decor_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focuspreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='enregistré le'),
        ),
    ]
