# Generated by Django 5.2.17 on 2026-09-06 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0013_progressevent'),
        ('sablier', '0012_universe_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='focussession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fin effective'),
        ),
        migrations.AddConstraint(
            model_name='focussession',
            constraint=models.UniqueConstraint(fields=('owner', 'client_id'), name='unique_focus_session_per_client'),
        ),
    ]
