"""Ressources pédagogiques choisies pour la L3 Mathématiques de Guyane.

Le catalogue reste dans le code plutôt qu'en base : une recommandation éditoriale n'est
pas encore une ressource personnelle. L'étudiant peut la consulter, puis importer tout le
parcours proposé dans sa bibliothèque. Les rattachements combinent trois ressources de
fond pour la matière et, quand le titre l'appelle, une ressource plus spécialisée.

Les URL pointent en priorité vers des universités, des organismes publics ou les auteurs
des outils. Le français est préféré à qualité comparable ; l'anglais est conservé quand
il donne accès à un parcours vidéo ou interactif sans équivalent aussi complet.
"""

from __future__ import annotations

import unicodedata
from dataclasses import dataclass

ROLE_LABELS = {
    "understand": "Comprendre",
    "watch": "Voir et écouter",
    "practice": "Pratiquer",
    "deepen": "Approfondir",
    "tool": "Outiller",
}

LANGUAGE_LABELS = {"fr": "Français", "en": "Anglais"}


@dataclass(frozen=True, slots=True)
class CuratedResource:
    key: str
    title: str
    url: str
    provider: str
    purpose: str
    role: str
    language: str
    format_label: str
    description: str

    @property
    def role_label(self) -> str:
        return ROLE_LABELS[self.role]

    @property
    def language_label(self) -> str:
        return LANGUAGE_LABELS[self.language]


@dataclass(frozen=True, slots=True)
class TopicRule:
    units: tuple[str, ...]
    terms: tuple[str, ...]
    resources: tuple[str, ...]


def _resource(
    key: str,
    title: str,
    url: str,
    provider: str,
    purpose: str,
    role: str,
    language: str,
    format_label: str,
    description: str,
) -> CuratedResource:
    return CuratedResource(key, title, url, provider, purpose, role, language, format_label, description)


RESOURCES = {
    item.key: item
    for item in (
        # ------------------------------------------------------------- topologie
        _resource(
            "topology_course_lille",
            "Cours de topologie",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/Cours-Topologie.pdf",
            "Université de Lille · E. Fricain",
            "course",
            "understand",
            "fr",
            "PDF de cours",
            "Un polycopié L3 structuré pour fixer définitions, caractérisations et preuves avant les exercices.",
        ),
        _resource(
            "topology_exercises_lille",
            "Exercices de topologie — premier fascicule",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/Fascicule-Topologie.pdf",
            "Université de Lille · E. Fricain",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Des exercices de niveau licence à traiter après la lecture du passage de cours correspondant.",
        ),
        _resource(
            "topology_exercises_advanced_lille",
            "Exercices de topologie — second fascicule",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/Fascicule2-Topo.pdf",
            "Université de Lille · E. Fricain",
            "exercise",
            "deepen",
            "fr",
            "PDF d'exercices",
            "Un second jeu de problèmes pour consolider les preuves et les résultats plus avancés du semestre.",
        ),
        # ------------------------------------------------ mesure et intégration
        _resource(
            "measure_course_lille",
            "Cours d'intégration",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/Cours-Integration.pdf",
            "Université de Lille · E. Fricain",
            "course",
            "understand",
            "fr",
            "PDF de cours",
            "Le fil complet mesure–fonctions mesurables–intégrale–convergences–espaces Lp au niveau L3.",
        ),
        _resource(
            "measure_exercises_lille",
            "Exercices d'intégration",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/Exo-Integration.pdf",
            "Université de Lille · E. Fricain",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Des TD assortis au cours pour apprendre à choisir le bon théorème et en vérifier les hypothèses.",
        ),
        _resource(
            "measure_td_exams_lyon",
            "Mesure et intégration L3 — cours, TD et examens",
            "https://math.univ-lyon1.fr/~mironescu/enseignement/EAF_L3.html",
            "Université Claude Bernard Lyon 1 · P. Mironescu",
            "past_paper",
            "deepen",
            "fr",
            "Cours, TD et annales",
            "Une seconde progression universitaire avec feuilles de TD et sujets d'examen pour se tester en temps limité.",
        ),
        # ----------------------------------------------------------- géométrie
        _resource(
            "geometry_affine_course_lyon",
            "Géométrie affine, projective et euclidienne",
            "https://math.univ-lyon1.fr/~aubrun/enseignement/L3-geometrie/L3geometrie.pdf",
            "Université Claude Bernard Lyon 1 · G. Aubrun",
            "course",
            "understand",
            "fr",
            "PDF de cours L3",
            "Le cours de référence : espaces et applications affines, barycentres, puis structure euclidienne et isométries.",
        ),
        _resource(
            "geometry_affine_practice_lyon",
            "Géométrie élémentaire L3 — TD, annales et figures",
            "https://math.univ-lyon1.fr/~germoni/L3/",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "exercise",
            "practice",
            "fr",
            "Cours, TD et annales",
            "Un parcours complet par feuilles : repères, applications affines, barycentres, euclidien, isométries et coniques.",
        ),
        _resource(
            "geometry_affine_summary_lyon",
            "Résumé de géométrie élémentaire",
            "https://math.univ-lyon1.fr/~germoni/L3/geom_elem_2013.pdf",
            "Université Claude Bernard Lyon 1 · S. Parmentier",
            "sheet",
            "deepen",
            "fr",
            "Synthèse PDF L3",
            "Une synthèse compacte pour réviser définitions, résultats et méthodes sans relire tout le polycopié.",
        ),
        _resource(
            "geometry_affine_transformations_lyon",
            "Applications affines — caractérisations, barycentres et groupe affine",
            "https://math.univ-lyon1.fr/~germoni/agreg/affines.pdf",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "course",
            "deepen",
            "fr",
            "Complément PDF",
            "Un complément ciblé sur la partie linéaire, les invariants, points fixes, projections et coordonnées barycentriques.",
        ),
        _resource(
            "geometry_affine_td_coordinates_lyon",
            "TD 1 — repères, équations de droites et de plans",
            "https://math.univ-lyon1.fr/~germoni/L3/TD_01.pdf",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Des exercices dédiés aux changements de repère, équations cartésiennes et paramétrages de sous-espaces affines.",
        ),
        _resource(
            "geometry_affine_td_barycentres_lyon",
            "TD 3 — applications affines et barycentres",
            "https://math.univ-lyon1.fr/~germoni/L3/TD_03.pdf",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Une feuille ciblée pour passer des définitions aux calculs d'applications affines et de barycentres.",
        ),
        _resource(
            "geometry_affine_video_caldero",
            "Géométrie affine, barycentres et convexité",
            "https://www.youtube.com/watch?v=m8XsfOx7UR4",
            "Philippe Caldero",
            "video",
            "watch",
            "fr",
            "Cours vidéo",
            "Une présentation orale exigeante qui relie barycentres, convexité et caractérisation des applications affines.",
        ),
        _resource(
            "geometry_affine_video_exo7",
            "Droite et plan — collection vidéo Exo7",
            "https://www.canal-u.tv/chaines/canal-unisciel/droite-et-plan",
            "Canal-U · Unisciel · Exo7",
            "video",
            "watch",
            "fr",
            "Collection de 9 vidéos",
            "Des exercices filmés et corrigés pour visualiser les calculs de droites, plans, distances et premières coniques.",
        ),
        _resource(
            "geometry_euclidean_td_lyon",
            "TD 6 — géométrie euclidienne",
            "https://math.univ-lyon1.fr/~germoni/L3/TD_06.pdf",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Produit scalaire, projections, distances, déterminants, angles et similitudes dans des problèmes guidés.",
        ),
        _resource(
            "geometry_euclidean_isometries_td_lyon",
            "TD 7 — géométrie euclidienne et isométries",
            "https://math.univ-lyon1.fr/~germoni/L3/TD_07.pdf",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "La feuille d'entraînement complémentaire pour transformations orthogonales, isométries et géométrie de l'espace.",
        ),
        _resource(
            "geometry_conics_td_lyon",
            "TD 10 — coniques",
            "https://math.univ-lyon1.fr/~germoni/L3/TD_10.pdf",
            "Université Claude Bernard Lyon 1 · J. Germoni",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Une feuille spécifique pour reconnaître, réduire et exploiter les équations des coniques.",
        ),
        _resource(
            "geometry_complex_video_exo7",
            "Nombres complexes — collection vidéo Exo7",
            "https://www.canal-u.tv/chaines/canal-unisciel/nombres-complexes",
            "Canal-U · Unisciel · Exo7",
            "video",
            "watch",
            "fr",
            "Collection vidéo",
            "Le rappel vidéo utile avant d'employer affixes, modules et arguments pour les similitudes et la géométrie plane.",
        ),
        # --------------------------------------------------------------- oraux
        _resource(
            "oral_presentation_mit",
            "Suggestions for a successful mathematics presentation",
            "https://ocw.mit.edu/courses/18-06ci-linear-algebra-communications-intensive-spring-2004/resources/talkhints/",
            "MIT OpenCourseWare",
            "sheet",
            "understand",
            "en",
            "Fiche méthode",
            "Une grille courte et concrète pour préparer le tableau, l'enchaînement des idées et la prise de parole.",
        ),
        _resource(
            "oral_writing_oxford",
            "How to Write Mathematics",
            "https://www.maths.ox.ac.uk/system/files/attachments/How%20to%20write%20mathematics.pdf",
            "University of Oxford · Mathematical Institute",
            "sheet",
            "practice",
            "en",
            "Guide PDF",
            "Un guide exigeant sur la précision, les notations et la continuité du raisonnement mathématique écrit.",
        ),
        _resource(
            "oral_checklist_mit",
            "Mathematical presentation checklist",
            "https://ocw.mit.edu/courses/18-821-project-laboratory-in-mathematics-spring-2013/pages/grading/",
            "MIT OpenCourseWare",
            "sheet",
            "deepen",
            "en",
            "Grille d'évaluation",
            "À utiliser pour une répétition filmée ou devant un pair, puis corriger un point précis à la fois.",
        ),
        # ------------------------------------------------- calcul scientifique
        _resource(
            "numerical_course_lille",
            "Calcul numérique — support de cours",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/francois_boulier/GIS4-CNUM/support.pdf",
            "Université de Lille · F. Boulier",
            "course",
            "understand",
            "fr",
            "PDF de cours",
            "Le socle théorique pour erreurs, racines, systèmes linéaires et comportement des méthodes numériques.",
        ),
        _resource(
            "scipy_lectures_pdf",
            "Python scientifique — SciPy Lecture Notes",
            "https://scipy-lectures.org/_downloads/ScipyLectures.pdf",
            "SciPy Lecture Notes",
            "exercise",
            "practice",
            "en",
            "PDF cours + exercices",
            "Un parcours éprouvé pour passer de l'algorithme mathématique à une expérimentation Python reproductible.",
        ),
        _resource(
            "numpy_operations",
            "Opérations NumPy et vectorisation",
            "https://scipy-lectures.org/intro/numpy/operations.html",
            "SciPy Lecture Notes",
            "tool",
            "tool",
            "en",
            "Tutoriel exécutable",
            "À garder ouvert pendant l'implémentation pour raisonner en tableaux plutôt qu'en boucles fragiles.",
        ),
        # --------------------------------------------------------- algorithmique
        _resource(
            "algorithms_inria",
            "Éléments d'algorithmique et de programmation",
            "https://pauillac.inria.fr/~levy/courses/25eaaaL1/",
            "Inria · B. Lévy",
            "course",
            "understand",
            "fr",
            "Cours et travaux pratiques",
            "Un cours français centré sur la construction, la justification et l'implémentation d'algorithmes.",
        ),
        _resource(
            "complexity_lille",
            "Introduction à la complexité algorithmique",
            "https://www.fil.univ-lille.fr/~varre/portail/graphes/docs/chap00-complexite.pdf",
            "Université de Lille",
            "course",
            "practice",
            "fr",
            "Chapitre PDF",
            "Un support compact pour apprendre à compter les opérations et comparer proprement deux algorithmes.",
        ),
        _resource(
            "graphs_lille",
            "Graphes L3 — cours et feuilles d'exercices",
            "https://portail.fil.univ-lille.fr/portail/index.php?dipl=L&sem=S5&ue=Graphes",
            "Université de Lille",
            "exercise",
            "deepen",
            "fr",
            "Cours, TD et TP",
            "Pour les parcours, plus courts chemins et preuves de correction sur des graphes de taille réaliste.",
        ),
        # -------------------------------------------------- systèmes dynamiques
        _resource(
            "dynamics_course_saclay",
            "Systèmes dynamiques et équations différentielles",
            "https://www.imo.universite-paris-saclay.fr/~claude.viterbo/Enseigt.html/Poly2009.pdf",
            "Université Paris-Saclay · C. Viterbo",
            "course",
            "understand",
            "fr",
            "PDF cours + exercices",
            "Un polycopié français complet avec portraits de phase, Grönwall, Poincaré-Bendixson, Lyapunov et exercices.",
        ),
        _resource(
            "differential_equations_mit",
            "Differential Equations — cours vidéo et problèmes corrigés",
            "https://ocw.mit.edu/courses/18-03sc-differential-equations-fall-2011/",
            "MIT OpenCourseWare",
            "video",
            "watch",
            "en",
            "Vidéos + exercices",
            "Un cours d'autoformation complet : vidéos, notes, exercices et solutions pour voir les dynamiques évoluer.",
        ),
        _resource(
            "nonlinear_dynamics_mit",
            "Nonlinear Dynamics I: Chaos",
            "https://ocw.mit.edu/courses/18-353j-nonlinear-dynamics-i-chaos-fall-2012/",
            "MIT OpenCourseWare",
            "course",
            "deepen",
            "en",
            "Cours, vidéos et problèmes",
            "Le complément pertinent pour cycles limites, bifurcations et phénomènes non linéaires.",
        ),
        # ------------------------------------------------ enseignement libre
        _resource(
            "zotero_quickstart",
            "Bien démarrer avec Zotero",
            "https://www.zotero.org/support/quick_start_guide",
            "Zotero",
            "tool",
            "tool",
            "en",
            "Guide officiel",
            "Pour collecter, classer, annoter puis citer les sources sans reconstruire la bibliographie à la main.",
        ),
        _resource(
            "hal_search",
            "Rechercher efficacement dans HAL",
            "https://doc.hal.science/rechercher-simple-avancee/",
            "HAL · CCSD",
            "sheet",
            "practice",
            "fr",
            "Tutoriel officiel",
            "Une méthode de recherche par auteur, mot-clé, discipline et texte intégral dans l'archive ouverte française.",
        ),
        _resource(
            "write_mathematics_oxford",
            "How to Write Mathematics",
            "https://www.maths.ox.ac.uk/system/files/attachments/How%20to%20write%20mathematics.pdf",
            "University of Oxford · Mathematical Institute",
            "sheet",
            "understand",
            "en",
            "Guide PDF",
            "Pour transformer des notes de lecture en restitution structurée, précise et réellement réutilisable.",
        ),
        # ------------------------------------------------------------- anglais
        _resource(
            "english_math_vocabulary",
            "English for Mathematics",
            "https://cm.pg.edu.pl/en/mathematics/vocabulary/english-mathematics",
            "Gdańsk University of Technology · Mathematics Centre",
            "course",
            "understand",
            "en",
            "Audio + exercices",
            "113 fichiers audio et exercices de compréhension pour relier vocabulaire, prononciation et notation.",
        ),
        _resource(
            "english_oxford_videos",
            "Introduction to University Mathematics",
            "https://www.maths.ox.ac.uk/node/61525",
            "University of Oxford · Mathematical Institute",
            "video",
            "watch",
            "en",
            "Cours vidéo",
            "Des mathématiques universitaires authentiques pour entraîner l'écoute sans sacrifier le contenu disciplinaire.",
        ),
        _resource(
            "english_math_writing",
            "How to Write Mathematics",
            "https://www.maths.ox.ac.uk/system/files/attachments/How%20to%20write%20mathematics.pdf",
            "University of Oxford · Mathematical Institute",
            "sheet",
            "practice",
            "en",
            "Guide PDF",
            "Un modèle concret pour rédiger définitions, preuves et résumés dans un anglais mathématique naturel.",
        ),
        _resource(
            "english_professional_email",
            "Email etiquette for students",
            "https://owl.purdue.edu/owl/general_writing/academic_writing/email_etiquette.html",
            "Purdue Online Writing Lab",
            "sheet",
            "practice",
            "en",
            "Guide pratique",
            "Une checklist ciblée pour l'objet, la formule d'appel, la demande et la clôture d'un courriel professionnel.",
        ),
        # ------------------------------------------------ calcul différentiel
        _resource(
            "differential_calculus_lyon",
            "Calcul différentiel L3",
            "https://math.univ-lyon1.fr/~benzoni/CD.pdf",
            "Université Claude Bernard Lyon 1 · S. Benzoni",
            "course",
            "understand",
            "fr",
            "PDF de cours",
            "Un cours L3 concis qui développe la différentiabilité, les théorèmes locaux et l'optimisation sous contraintes.",
        ),
        _resource(
            "differential_calculus_exercises_lille",
            "Exercices de calcul différentiel",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/exo-calcul-diff.pdf",
            "Université de Lille · E. Fricain",
            "exercise",
            "practice",
            "fr",
            "PDF d'exercices",
            "Des problèmes de niveau L3 pour passer du calcul formel à la rédaction complète des hypothèses et conclusions.",
        ),
        _resource(
            "multivariable_calculus_mit",
            "Multivariable Calculus — vidéos, problèmes et solutions",
            "https://ocw.mit.edu/courses/18-02sc-multivariable-calculus-fall-2010/",
            "MIT OpenCourseWare",
            "video",
            "watch",
            "en",
            "Cours vidéo interactif",
            "Les animations, vidéos de résolution et Mathlets rendent gradients, Hessiennes et extrema plus visibles.",
        ),
        # ---------------------------------------------------- probabilités
        _resource(
            "probability_lyon",
            "Probabilités L3 — notes, TD et examens",
            "https://math.univ-lyon1.fr/~aubrun/enseignement/IFL3-probas/index.html",
            "Université Claude Bernard Lyon 1 · G. Aubrun",
            "course",
            "understand",
            "fr",
            "Cours, TD et annales",
            "Un cours L3 récent accompagné de feuilles de TD et d'examens pour travailler toute la chaîne probabiliste.",
        ),
        _resource(
            "probability_unisciel",
            "Probabilités — exercices interactifs",
            "https://ressources.unisciel.fr/ramses/519-21_probabilites/co/module_519-21_5.html",
            "Unisciel",
            "exercise",
            "practice",
            "fr",
            "Exercices interactifs",
            "Une pratique guidée avec retour immédiat pour automatiser les calculs avant les preuves de niveau L3.",
        ),
        _resource(
            "probability_videos_mit",
            "Applied Probability — conférences vidéo",
            "https://ocw.mit.edu/courses/6-041-probabilistic-systems-analysis-and-applied-probability-fall-2010/video_galleries/video-lectures/",
            "MIT OpenCourseWare",
            "video",
            "watch",
            "en",
            "Cours vidéo",
            "Une série structurée qui visualise conditionnement, indépendance, variables aléatoires et lois limites.",
        ),
        # --------------------------------------------------- analyse complexe
        _resource(
            "complex_analysis_lyon",
            "Analyse complexe — cours complet",
            "https://math.univ-lyon1.fr/~iftimie/enseignement/poly-anac-2023.pdf",
            "Université Claude Bernard Lyon 1 · D. Iftimie",
            "course",
            "understand",
            "fr",
            "PDF de cours",
            "Un polycopié cohérent de l'holomorphie jusqu'aux résidus et aux applications globales.",
        ),
        _resource(
            "complex_analysis_exercises_lille",
            "Analyse complexe — exercices et annales",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/emmanuel_fricain/fascicule.pdf",
            "Université de Lille · E. Fricain",
            "exercise",
            "practice",
            "fr",
            "PDF exercices + annales",
            "Des exercices gradués et des sujets d'examen pour vérifier la maîtrise sans rester dans la lecture du cours.",
        ),
        _resource(
            "complex_analysis_videos_mit",
            "Complex Variables — vidéos, guides et exercices corrigés",
            "https://ocw.mit.edu/courses/res-18-008-calculus-revisited-complex-variables-differential-equations-and-linear-algebra-fall-2011/video_galleries/part-i/",
            "MIT OpenCourseWare",
            "video",
            "watch",
            "en",
            "Vidéos + exercices",
            "Un parcours visuel resserré sur les variables complexes, avec guides d'étude et solutions à chaque étape.",
        ),
        _resource(
            "complex_cauchy_riemann_bibmath",
            "Exercices corrigés — équations de Cauchy-Riemann",
            "https://www.bibmath.net/ressources/index.php?action=affiche&quoi=bde%2Fanalyse%2Fvc%2Fcauchyriemann&type=fexo",
            "Bibm@th",
            "solution",
            "deepen",
            "fr",
            "Exercices corrigés",
            "Un entraînement ciblé pour décider correctement de la dérivabilité complexe et de l'holomorphie.",
        ),
        _resource(
            "complex_residues_bibmath",
            "Exercices corrigés — résidus",
            "https://www.bibmath.net/ressources/index.php?action=affiche&quoi=bde%2Fanalyse%2Fvc%2Fresidus&type=fexo",
            "Bibm@th",
            "solution",
            "deepen",
            "fr",
            "Exercices corrigés",
            "Des calculs ciblés pour choisir le bon développement et transformer les résidus en outil de calcul.",
        ),
        _resource(
            "complex_zeros_bibmath",
            "Exercices corrigés — zéros et théorème de Rouché",
            "https://www.bibmath.net/ressources/index.php?action=affiche&quoi=bde%2Fanalyse%2Fvc%2Fzeros&type=fexo",
            "Bibm@th",
            "solution",
            "deepen",
            "fr",
            "Exercices corrigés",
            "Des problèmes spécifiques sur l'identité analytique, le comptage des zéros et le théorème de Rouché.",
        ),
        _resource(
            "complex_major_theorems_bibmath",
            "Exercices corrigés — grands théorèmes holomorphes",
            "https://www.bibmath.net/ressources/index.php?action=affiche&quoi=bde%2Fanalyse%2Fvc%2Fgdsthms&type=fexo",
            "Bibm@th",
            "solution",
            "deepen",
            "fr",
            "Exercices corrigés",
            "Pour apprendre à reconnaître quand employer Liouville, le principe du maximum ou les zéros isolés.",
        ),
        # --------------------------------------------------- analyse numérique
        _resource(
            "numerical_analysis_course_lille",
            "Calcul numérique — support de cours",
            "https://pro.univ-lille.fr/fileadmin/user_upload/pages_pros/francois_boulier/GIS4-CNUM/support.pdf",
            "Université de Lille · F. Boulier",
            "course",
            "understand",
            "fr",
            "PDF de cours",
            "Un support théorique pour comprendre approximation, stabilité, erreurs et choix d'une méthode.",
        ),
        _resource(
            "numerical_analysis_scipy",
            "SciPy Lecture Notes — calcul scientifique",
            "https://scipy-lectures.org/intro/scipy.html",
            "SciPy Lecture Notes",
            "exercise",
            "practice",
            "en",
            "Tutoriels + exemples",
            "Des exemples reproductibles pour confronter l'algorithme étudié à une implémentation scientifique fiable.",
        ),
        _resource(
            "numerical_analysis_scipy_pdf",
            "SciPy Lecture Notes — version PDF",
            "https://scipy-lectures.org/_downloads/ScipyLectures.pdf",
            "SciPy Lecture Notes",
            "sheet",
            "deepen",
            "en",
            "PDF cours + exercices",
            "Une référence téléchargeable pour préparer une séance, annoter les méthodes et conserver les exemples.",
        ),
        _resource(
            "scipy_interpolation",
            "Interpolation avec SciPy",
            "https://docs.scipy.org/doc/scipy/tutorial/interpolate.html",
            "SciPy",
            "tool",
            "tool",
            "en",
            "Documentation + exemples",
            "Pour expérimenter interpolation polynomiale, splines et comportement entre les nœuds.",
        ),
        _resource(
            "scipy_integration",
            "Intégration numérique et EDO avec SciPy",
            "https://docs.scipy.org/doc/scipy/tutorial/integrate.html",
            "SciPy",
            "tool",
            "tool",
            "en",
            "Documentation + exemples",
            "Pour vérifier quadratures et intégrateurs d'EDO sur des cas dont on connaît la solution ou l'erreur.",
        ),
        _resource(
            "numpy_linear_algebra",
            "Algèbre linéaire NumPy",
            "https://numpy.org/doc/stable/reference/routines.linalg.html",
            "NumPy",
            "tool",
            "tool",
            "en",
            "Référence officielle",
            "Pour comparer QR, Cholesky, valeurs propres et résolution sans confondre formule théorique et API.",
        ),
        # ------------------------------------------------ statistiques appliquées
        _resource(
            "statistics_inria",
            "Statistics in Action with R",
            "https://compo.inria.fr/sia/",
            "Inria",
            "course",
            "understand",
            "en",
            "Cours + études de données",
            "La théorie statistique reliée à des études réelles sous R, avec une attention portée à l'interprétation.",
        ),
        _resource(
            "statistics_r_french",
            "Mini-tutoriel R pour l'analyse de données",
            "https://who.paris.inria.fr/Jean-Marc.Lasgouttes/ana-donnees/2022/cours-mini_r.pdf",
            "Inria · J.-M. Lasgouttes",
            "tool",
            "practice",
            "fr",
            "Tutoriel PDF",
            "Un démarrage compact en français pour produire calculs, graphiques et scripts statistiques réutilisables.",
        ),
        _resource(
            "statistics_teaching_lyon",
            "Ressources d'enseignement en statistique",
            "https://pbil.univ-lyon1.fr/members/fpicard/teaching.html",
            "Université Claude Bernard Lyon 1 · F. Picard",
            "exercise",
            "deepen",
            "fr",
            "Cours et travaux pratiques",
            "Des supports universitaires supplémentaires pour passer d'une formule à une analyse complète de données.",
        ),
        _resource(
            "statistics_estimation_lyon",
            "Estimation statistique",
            "https://mathsv.univ-lyon1.fr/app/cours/?chap=6&theme=proba",
            "Université Claude Bernard Lyon 1 · MathSV",
            "course",
            "deepen",
            "fr",
            "Cours interactif",
            "Un rappel ciblé sur estimateurs, biais, intervalles et qualité d'une estimation.",
        ),
        _resource(
            "statistics_tests_lyon",
            "Tests statistiques",
            "https://mathsv.univ-lyon1.fr/app/cours/?chap=7&theme=proba",
            "Université Claude Bernard Lyon 1 · MathSV",
            "course",
            "deepen",
            "fr",
            "Cours interactif",
            "Une progression ciblée pour poser les hypothèses, choisir la statistique et interpréter la décision.",
        ),
        _resource(
            "statistics_regression_lyon",
            "Régression linéaire",
            "https://pbil.univ-lyon1.fr/members/fpicard/franckpicard_fichiers/pdf/siab5.pdf",
            "Université Claude Bernard Lyon 1 · F. Picard",
            "course",
            "deepen",
            "fr",
            "Chapitre PDF",
            "Un support consacré au modèle, à l'estimation, aux tests de coefficients et au diagnostic des résidus.",
        ),
        # ------------------------------------------------------ projet numérique
        _resource(
            "project_jupyter",
            "Découvrir Jupyter Notebook",
            "https://jupyter.org/try-jupyter/notebooks/?path=notebooks%2FIntro.ipynb",
            "Project Jupyter",
            "notebook",
            "tool",
            "en",
            "Notebook interactif",
            "Pour réunir code, résultats, figures, équations et explications dans un livrable exécutable.",
        ),
        _resource(
            "project_github",
            "Bien démarrer avec un dépôt GitHub",
            "https://docs.github.com/fr/repositories/creating-and-managing-repositories/quickstart-for-repositories?tool=cli",
            "GitHub Docs",
            "tool",
            "practice",
            "fr",
            "Tutoriel officiel",
            "Pour versionner le travail dès le début et conserver des étapes vérifiables plutôt qu'un unique fichier final.",
        ),
        _resource(
            "project_writing_mit",
            "Writing a mathematics project",
            "https://ocw.mit.edu/courses/18-821-project-laboratory-in-mathematics-spring-2013/pages/writing/",
            "MIT OpenCourseWare",
            "sheet",
            "understand",
            "en",
            "Guide + exemples",
            "Une méthode universitaire pour transformer expériences et calculs en rapport argumenté et reproductible.",
        ),
        # ------------------------------------------------ préprofessionnalisation
        _resource(
            "career_math_onisep",
            "Licence mathématiques — spécialisations et débouchés",
            "https://www.onisep.fr/formation/les-principaux-domaines-de-formation/les-licences-de-sciences/la-licence-mathematiques",
            "Onisep",
            "external",
            "understand",
            "fr",
            "Dossier d'orientation",
            "Un panorama officiel des spécialisations L3, poursuites d'études et secteurs accessibles après la licence.",
        ),
        _resource(
            "teaching_math_eduscol",
            "Ressources pour enseigner les mathématiques",
            "https://eduscol.education.gouv.fr/4509/mathematiques",
            "Éduscol · Ministère de l'Éducation nationale",
            "external",
            "practice",
            "fr",
            "Programmes et ressources",
            "Le point d'entrée officiel pour programmes, attendus, progressions, activités et ressources d'accompagnement.",
        ),
        _resource(
            "capes_reference_2026",
            "Référentiel de formation — professorat du second degré, mathématiques",
            "https://www.education.gouv.fr/sites/default/files/document/annexe-10-referentiel-de-formation-professorat-du-second-degre-mathematiques-capes-516695.pdf",
            "Ministère de l'Éducation nationale",
            "course",
            "deepen",
            "fr",
            "Référentiel PDF",
            "Le cadre officiel actuel pour relier contenus mathématiques, didactique, numérique et compétences du métier.",
        ),
        _resource(
            "career_cv_apec",
            "Adapter son CV à une offre",
            "https://www.apec.fr/candidat/etre-accompagne-dans-votre-recherche-demploi/1er-emploi/fiche-conseils/adapter-son-cv-par-rapport-a-une-offre-demploi-pour-le-rendre-plus-attractif.html",
            "Apec",
            "sheet",
            "practice",
            "fr",
            "Guide pratique",
            "Une méthode destinée aux jeunes diplômés pour sélectionner et formuler les preuves de ses compétences.",
        ),
        _resource(
            "career_interview_apec",
            "Skynesis — préparer son premier emploi",
            "https://www.apec.fr/candidat/etre-accompagne-dans-votre-recherche-demploi/1er-emploi/fiches-transactions/application-premier-emploi-skynesis.html",
            "Apec",
            "tool",
            "practice",
            "fr",
            "Serious game + simulateurs",
            "Des mises en situation, simulateurs d'entretien et conseils concrets pour préparer sa présentation.",
        ),
        _resource(
            "career_statistician_apec",
            "Statisticien — missions et compétences",
            "https://www.apec.fr/tous-nos-metiers/etudes-recherche-et-developpement/statisticien.html",
            "Apec",
            "external",
            "deepen",
            "fr",
            "Fiche métier",
            "Un exemple détaillé de traduction des acquis mathématiques en activités, outils et compétences professionnelles.",
        ),
    )
}


# Trois ressources de fond par matière : elles se complètent par le rôle, pas par le titre.
UNIT_BUNDLES = {
    "Topologie": ("topology_course_lille", "topology_exercises_lille", "topology_exercises_advanced_lille"),
    "Mesure et intégration": ("measure_course_lille", "measure_exercises_lille", "measure_td_exams_lyon"),
    "Géométrie": (
        "geometry_affine_course_lyon",
        "geometry_affine_practice_lyon",
        "geometry_affine_summary_lyon",
    ),
    "Oraux de mathématiques": ("oral_presentation_mit", "oral_writing_oxford", "oral_checklist_mit"),
    "Calcul scientifique 5": ("numerical_course_lille", "scipy_lectures_pdf", "numpy_operations"),
    "Algorithmique et programmation 5": ("algorithms_inria", "complexity_lille", "graphs_lille"),
    "Systèmes dynamiques": ("dynamics_course_saclay", "differential_equations_mit", "nonlinear_dynamics_mit"),
    "Enseignement libre": ("write_mathematics_oxford", "hal_search", "zotero_quickstart"),
    "Anglais": ("english_math_vocabulary", "english_oxford_videos", "english_math_writing"),
    "Calcul différentiel": (
        "differential_calculus_lyon",
        "differential_calculus_exercises_lille",
        "multivariable_calculus_mit",
    ),
    "Mesure et probabilités": ("probability_lyon", "probability_unisciel", "probability_videos_mit"),
    "Analyse complexe": (
        "complex_analysis_lyon",
        "complex_analysis_exercises_lille",
        "complex_analysis_videos_mit",
    ),
    "Analyse numérique": (
        "numerical_analysis_course_lille",
        "numerical_analysis_scipy",
        "numerical_analysis_scipy_pdf",
    ),
    "Statistiques appliquées": ("statistics_inria", "statistics_r_french", "statistics_teaching_lyon"),
    "Projet numérique": ("project_writing_mit", "project_github", "project_jupyter"),
    "Préprofessionnalisation": ("career_math_onisep", "teaching_math_eduscol", "capes_reference_2026"),
}


TOPIC_RULES = (
    TopicRule(
        ("Géométrie",),
        (
            "espace affine",
            "sous-espace affine",
            "enveloppe affine",
            "independance affine",
            "application affine",
            "applications affines",
            "point fixe",
            "translation",
            "homothetie",
            "projection affine",
            "symetrie affine",
            "invariants affines",
        ),
        ("geometry_affine_transformations_lyon",),
    ),
    TopicRule(
        ("Géométrie",),
        ("repere affine", "changement de repere", "equations parametriques", "droites, plans", "intersection"),
        ("geometry_affine_td_coordinates_lyon", "geometry_affine_video_exo7"),
    ),
    TopicRule(
        ("Géométrie",),
        ("barycentre", "barycentres", "barycentriques", "simplexe", "combinaison convexe", "enveloppe convexe"),
        ("geometry_affine_td_barycentres_lyon", "geometry_affine_video_caldero"),
    ),
    TopicRule(
        ("Géométrie",),
        (
            "euclidien",
            "orthogonal",
            "orthonormee",
            "distance",
            "mediatric",
            "sphere",
            "angle",
            "aires",
            "volumes",
        ),
        ("geometry_euclidean_td_lyon",),
    ),
    TopicRule(
        ("Géométrie",),
        ("isometrie", "isometries", "matrice orthogonale", "reflexions", "rotations", "groupe des isometries"),
        ("geometry_euclidean_isometries_td_lyon",),
    ),
    TopicRule(
        ("Géométrie",),
        ("similitude", "similitudes", "nombres complexes", "triangle", "cercle"),
        ("geometry_complex_video_exo7", "geometry_euclidean_td_lyon"),
    ),
    TopicRule(
        ("Géométrie",),
        ("conique", "coniques", "quadrique", "quadriques", "ellipsoide", "hyperboloide", "paraboloide"),
        ("geometry_conics_td_lyon", "geometry_affine_video_exo7"),
    ),
    TopicRule(
        ("Analyse complexe",),
        ("cauchy-riemann", "c-derivabilite", "holomorphie", "harmonique"),
        ("complex_cauchy_riemann_bibmath",),
    ),
    TopicRule(
        ("Analyse complexe",),
        ("residu", "laurent", "singularite", "integrale reelle"),
        ("complex_residues_bibmath",),
    ),
    TopicRule(
        ("Analyse complexe",),
        ("rouche", "zeros isoles", "prolonger analytiquement"),
        ("complex_zeros_bibmath",),
    ),
    TopicRule(
        ("Analyse complexe",),
        ("liouville", "principe du maximum", "theoreme fondamental"),
        ("complex_major_theorems_bibmath",),
    ),
    TopicRule(
        ("Analyse numérique",),
        ("interpolation", "spline", "runge", "tchebychev", "hermite"),
        ("scipy_interpolation",),
    ),
    TopicRule(
        ("Analyse numérique",),
        ("quadrature", "integrale", "euler", "runge-kutta", "equation differentielle", "probleme raide"),
        ("scipy_integration",),
    ),
    TopicRule(
        ("Analyse numérique",),
        ("qr", "gram-schmidt", "cholesky", "valeur propre", "spectre"),
        ("numpy_linear_algebra",),
    ),
    TopicRule(
        ("Statistiques appliquées",),
        ("estimateur", "biais", "vraisemblance", "fisher", "cramer-rao", "intervalle de confiance"),
        ("statistics_estimation_lyon",),
    ),
    TopicRule(
        ("Statistiques appliquées",),
        ("test", "p-valeur", "student", "khi-deux", "variance", "analyse de la variance"),
        ("statistics_tests_lyon",),
    ),
    TopicRule(
        ("Statistiques appliquées",),
        ("regression", "residus"),
        ("statistics_regression_lyon",),
    ),
    TopicRule(("Anglais",), ("courriel",), ("english_professional_email",)),
    TopicRule(
        ("Préprofessionnalisation",),
        ("cv", "lettre de motivation"),
        ("career_cv_apec",),
    ),
    TopicRule(("Préprofessionnalisation",), ("entretien",), ("career_interview_apec",)),
    TopicRule(
        ("Préprofessionnalisation",),
        ("metiers", "entreprise", "projet professionnel"),
        ("career_statistician_apec",),
    ),
)


def _normalise(value: str) -> str:
    decomposed = unicodedata.normalize("NFKD", value)
    return "".join(character for character in decomposed if not unicodedata.combining(character)).casefold()


def recommendations_for(title: str, unit_titles: list[str] | tuple[str, ...]) -> list[CuratedResource]:
    """Retourne un parcours court, ordonné et sans doublon pour une compétence."""
    keys: list[str] = []
    for unit_title in unit_titles:
        keys.extend(UNIT_BUNDLES.get(unit_title, ()))

    normalised_title = _normalise(title)
    units = set(unit_titles)
    for rule in TOPIC_RULES:
        if units.intersection(rule.units) and any(term in normalised_title for term in rule.terms):
            keys.extend(rule.resources)

    unique_keys = list(dict.fromkeys(keys))
    return [RESOURCES[key] for key in unique_keys]


def recommendations_for_competency(competency) -> list[CuratedResource]:
    """Adapte la fonction pure à un objet ``Competency`` déjà chargé ou ordinaire."""
    unit_titles = list(competency.units.values_list("title", flat=True))
    return recommendations_for(competency.title, unit_titles)
